name: Update Package Dependencies

on: 
  workflow_dispatch:
    inputs:
      token:
        description: 'Token'
        required: true
      packageName:
        description: 'Package to update'
        required: false
      version:
        description: 'Version to update to'
        required: false
        default: 'latest'
      owner:
        description: 'Owner'
        required: false
      repo:
        description: 'Repository'
        required: false
      branchName:
        description: 'Branch name to create'
        required: false
        default: 'deps/update-packages'
      baseBranch:
        description: 'Base branch'
        required: false
        default: 'main'
  
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.owner }}/${{ inputs.repo }}
          token: ${{ inputs.token }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          token: ${{ inputs.token }}

      - name: Update Dependencies
        run: |
          npm install ${{ inputs.packageName }}@${{ inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ inputs.token }}
          title: Update ${{ inputs.packageName }} to ${{ inputs.version }}
          body: |
            This PR updates ${{ inputs.packageName }} to ${{ inputs.version }}.
          base: main
          branch: ${{ inputs.branchName }}
          commit-message: Update ${{ inputs.packageName }} to ${{ inputs.version }}

